# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6b8a76dae3c058fedf33ababad845fd16be96e79fec2c6f66701f3c31354b9b7b50dda225735c623026e8ba8fded1471e60376e0f3db9a27738f2dfddb360d5

test:
  secret_key_base: 842ec467b647009abd4c6c6ebf3d09801b77abdb9836133d72c0c1cb1cf642bfbbb6b61b31c0578fb05c744e95cb6c842111330972585011039d0a0a113893c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
